language: go
sudo: required

go:
  - "1.13"

env:
  global:
    - PATH=$GOROOT/bin:$GOPATH/bin:$PATH

before_script:
  - go get -u github.com/mattn/goveralls

script:
  - make lint
  - make test-coverage
  - goveralls -coverprofile=rdma-cni.cover -service=travis-ci
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  # Push image to Dockerhub on merge to master
  - provider: script
    skip_cleanup: true
    script: >
      bash -c '
      docker push $IMAGE_NAME
      echo Done'
    on:
      branch: master
  # Push image to Dockerhub on tag
  - provider: script
    skip_cleanup: true
    script: >
      bash -c '
      docker tag $IMAGE_NAME $IMAGE_NAME:$TRAVIS_TAG;
      docker push $IMAGE_NAME:$TRAVIS_TAG;
      echo Done'
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
